version: '3'

services:
  app:
    build: 2.1
    container_name: app
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - monitoring

#  blackbox-exporter:
#    image: prom/blackbox-exporter:latest
#    container_name: blackbox-exporter
#    volumes:
#      - ./blackbox.yml:/etc/blackbox/blackbox.yml
#    ports:
#      - "9115:9115"
#    networks:
#      - monitoring
#    command:
#      - '--config.file=/etc/blackbox/blackbox.yml'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

networks:
  monitoring:
    driver: bridge